---
title: "Regresión Logística"
author: "Pedro Guzmán, Gustavo Cruz"
date: "2025-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning=FALSE)
```

```{r}
# Chunk para librerias
library(ggplot2)
library(caret)
library(dplyr)
library(car)

```
# Regresión logística

## Creación de las variables dicotómicas

Para cerar la variable dicotómica, se usará la variable "Cateogry" creada en ejercicios anteriores, los valores de esta variable determinaran los valores de las nuevas variables dicotómicas. 
```{r}
train <- read.csv("train.csv")

set.seed(245)
porciento <- 0.7
corte <- sample(nrow(train),nrow(train) * porciento)
train <- train[corte, ]
test <- train[-corte, ]

training_data <- read.csv("train.csv")
set.seed(245)
porciento <- 0.7
corte <- sample(nrow(training_data),nrow(training_data) * porciento)
training_data <- training_data[corte, ]
test_data <- training_data[-corte, ]
mean_price <- mean(training_data$SalePrice, na.rm = TRUE)
sd_price <- sd(training_data$SalePrice, na.rm = TRUE)
lower_limit <- median(training_data$SalePrice)
upper_limit <- mad(training_data$SalePrice)

training_data$Category <- ifelse(training_data$SalePrice < (lower_limit - upper_limit), "Baratas",
                                 ifelse(training_data$SalePrice > (lower_limit + upper_limit), "Caras", "Medianas"))

test_data$Category <- ifelse(test_data$SalePrice < (lower_limit - upper_limit), "Baratas",
                             ifelse(test_data$SalePrice > (lower_limit + upper_limit), "Caras", "Medianas"))


training_data <- training_data %>%
  mutate(
    Barata = ifelse(Category == "Baratas", 1, 0),
    Mediana  = ifelse(Category == "Medianas", 1, 0),
    Cara   = ifelse(Category == "Caras", 1, 0)
  )

test_data <- test_data %>%
  mutate(
    Barata = ifelse(Category == "Baratas", 1, 0),
    Mediana  = ifelse(Category == "Medianas", 1, 0),
    Cara   = ifelse(Category == "Caras", 1, 0)
  )


```

